spring:
# DB config in prod
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

# App properties in prod
app:
  short-url-properties:
    base-url: ${APP_BASE_URL}