server:
  port: ${PORT:8080}
spring:
# DB config in prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5  # free tier limits connections
  jpa:
    hibernate:
      ddl-auto: validate  # Flyway's managing the schema
    properties:
      hibernate:
        default_schema: linkshade
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: linkshade

logging:
  level:
    de.linkshade: INFO

# App properties in prod
app:
  check-http-status-code: true
  enable-delete-account: false
  short-url-properties:
    base-url: ${APP_BASE_URL}